### PR TITLE
Basics

### PR DESCRIPTION
**Pull request by purohitmansi**

### CODE REVIEW

**Review by BaXCruiser — CHANGES_REQUESTED** [review]
Great work ,
but it is a basic practice to keep the java file name same as the class name(inside that class).
for example if i create a Student class then the name of the java file would be Student.java
and use some meaningful name :)

**Comment by purohitmansi** [comment]
Okay I will correct it.

**Review by BaXCruiser — CHANGES_REQUESTED** [review]
I Still se that your java file name is Java Bean Employee but class name is just Employee.
you can rename the java file as JavaBeanEmployee and classname also as JavaBeanEmployee for more verbosity .
correct all classnames and update the PR

**Comment by purohitmansi** [comment]
> I Still se that your java file name is Java Bean Employee but class name is just Employee.
> you can rename the java file as JavaBeanEmployee and classname also as JavaBeanEmployee for more verbosity .
> correct all classnames and update the PR

Done.

**Review by BaXCruiser — APPROVED** [review]

**Pull request merged**
