### PR TITLE
if , if-else , if -else-if .

### PR DESCRIPTION
**Pull request by Mayuri-cell**
Topic: if , if-else, if-else-if statements .
Name: Mayuri Mahajan

Description
This work is about if ,if - else , if-else-if .
This work contains,

README.md : Contains explanation and example.
else-if.java : Contains example code.

### CODE REVIEW

**Comment by Mayuri-cell** [comment]
[https://github.com/Learn-Write-Repeat/java/pull/27#issue-704422919](url)

**Comment by Mayuri-cell** [comment]
https://github.com/Learn-Write-Repeat/java/pull/27#issue-704422919

**Review by BaXCruiser — CHANGES_REQUESTED** [review]
else if is a combined statement-
if(condition){}
else if(condition){}
else

you are nesting here, update the PR with the changes

**Comment by Mayuri-cell** [comment]
I have made the changes .  I updated file with else -if .

**Review by BaXCruiser — APPROVED** [review]

**Pull request merged**
