### PR TITLE
inheritance

### PR DESCRIPTION
**Pull request by dilroseR**
<html>
<body>
<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px !important; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Contribution Information</h2>

Week | Day | Topic | Name
-- | -- | -- | --
2 | 1 | Inheritance | Dilrose Reji

### Description
This work is about inheritance
This work contains,

README.md : Contains explanation and example.
Inheritance.java : Contains example code.
</body>
</html>

### CODE REVIEW

**Review by BaXCruiser — CHANGES_REQUESTED** [review]
>java does not supports multiple inheritance but it can be achieved by use of interfaces, on class can implement multiple interfaces.
>are you sure that java only supports single and multilevel inheritance.
>can we have examples for other types of inheritance as well !.

**Comment by dilroseR** [comment]
> > java does not supports multiple inheritance but it can be achieved by use of interfaces, on class can implement multiple interfaces.
> > are you sure that java only supports single and multilevel inheritance.
> > can we have examples for other types of inheritance as well !.

instead of muultiple we have interfaces but i didn't include that because i'll cover interfaces in abstraction

**Comment by dilroseR** [comment]
is that ok?

**Comment by BaXCruiser** [comment]
what about the other 2 points

**Comment by dilroseR** [comment]
> what about the other 2 points

i didn't get you. Can you elaborate!

**Comment by BaXCruiser** [comment]
are you sure that java only supports single and multilevel inheritance.
and
can we have examples for other types of inheritance as well !

**Comment by dilroseR** [comment]
> are you sure that java only supports single and multilevel inheritance.
> and
> can we have examples for other types of inheritance as well !

ill try giving examples

**Comment by dilroseR** [comment]
added examples

**Review by BaXCruiser — APPROVED** [review]

**Pull request merged**
