### PR TITLE
WHILE & DO WHILE LOOPS

### PR DESCRIPTION
**Pull request by dilroseR**
<html>
<body>
<h2 style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px !important; font-weight: 600; font-size: 1.5em; line-height: 1.25; border-bottom: 1px solid var(--color-border-secondary); padding-bottom: 0.3em; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Contribution Information</h2>

Week | Day | Topic | Name
-- | -- | -- | --
2 | 4 | While & Do while loops | Dilrose Reji

### Description
This work is about while and do while loops
This work contains,

README.md : Contains explanation and example.
While.java : Contains example code.
DoWhile.java : Contains example code.</body>
</html>

### CODE REVIEW

**Review by BaXCruiser — CHANGES_REQUESTED** [review]
Hi ,
loops consist of 4 parts
initialization expression (initializing the loop variable)
conditional expression (limit for the loop to run )
update expression (increment/decrement of looping variable )
and loop body

Can you please update the syntax for the loops  and update the PR with the changes

**Comment by dilroseR** [comment]
> Hi ,
> loops consist of 4 parts
> initialization expression (initializing the loop variable)
> conditional expression (limit for the loop to run )
> update expression (increment/decrement of looping variable )
> and loop body
> 
> Can you please update the syntax for the loops and update the PR with the changes

yes i'll do that 
will update it

**Comment by dilroseR** [comment]
> > Hi ,
> > loops consist of 4 parts
> > initialization expression (initializing the loop variable)
> > conditional expression (limit for the loop to run )
> > update expression (increment/decrement of looping variable )
> > and loop body
> > Can you please update the syntax for the loops and update the PR with the changes
> 
> yes i'll do that
> will update it

hi @BaXCruiser I've updated

**Review by BaXCruiser — APPROVED** [review]

**Comment by dilroseR** [comment]
there is no form to fill about successful merging of pr right?

**Pull request merged**
