### PR TITLE
Day 1 Sreelakshmi

### PR DESCRIPTION
**Pull request by sreelakshmig009**

### CODE REVIEW

**Comment by BaXCruiser** [comment]
Hi Sreelakshmi,
The folder name should be the topic name instead of Day 1 and the files should be of .md or .java or both.
please update the PR with the changes i suggested you ,
for reference you can have a look at one of the PR I've merged in master , that will help you.

**Comment by sreelakshmig009** [comment]
https://github.com/sreelakshmig009/java/tree/day-1-sreelakshmi I have made those changes

**Comment by BaXCruiser** [comment]
update the PR

**Comment by BaXCruiser** [comment]
Great thanks 🙂

**Pull request merged**
